/**
 * AI Visibility checker (AEO/GEO) — can ChatGPT / Claude / Perplexity / Google AI
 * reach, understand, and quote this store?
 *
 * Criteria follow the in-house SEO/AEO/GEO standard (seo-marketing-site skill §6):
 * welcome answer/retrieval bots in robots.txt, publish a well-formed llms.txt,
 * expose Organization/WebSite structured data, keep content server-rendered, and
 * make it discoverable (sitemap). Also generates a skill-compliant starter llms.txt.
 */

import type { ToolCheck, ToolResult, ToolStatus } from "../types";
import { fetchPage, fetchText, host } from "../http";
import { scoreChecks, gradeFromScore } from "../score";
import {
  getTitle,
  getMetaName,
  getJsonLdTypes,
  hrefsMatching,
  looksBlocked,
} from "@/lib/grader/html";

/** Answer/retrieval bots that matter for AI-search visibility (skill §6a). */
const AI_BOTS = [
  { ua: "gptbot", name: "GPTBot" },
  { ua: "oai-searchbot", name: "OAI-SearchBot" },
  { ua: "chatgpt-user", name: "ChatGPT-User" },
  { ua: "claudebot", name: "ClaudeBot" },
  { ua: "claude-web", name: "Claude-Web" },
  { ua: "anthropic-ai", name: "anthropic-ai" },
  { ua: "perplexitybot", name: "PerplexityBot" },
  { ua: "perplexity-user", name: "Perplexity-User" },
  { ua: "google-extended", name: "Google-Extended" },
  { ua: "applebot-extended", name: "Applebot-Extended" },
  { ua: "ccbot", name: "CCBot" },
  { ua: "cohere-ai", name: "cohere-ai" },
];

/** Parse robots.txt into UA (lowercased) → disallow paths; also collect sitemaps. */
function parseRobots(robots: string): { rules: Map<string, string[]>; sitemaps: string[] } {
  const rules = new Map<string, string[]>();
  const sitemaps: string[] = [];
  let current: string[] = [];
  for (const raw of robots.split("\n")) {
    const line = raw.split("#")[0].trim();
    if (!line) continue;
    const [k, ...rest] = line.split(":");
    const key = k.trim().toLowerCase();
    const val = rest.join(":").trim();
    if (key === "user-agent") {
      const ua = val.toLowerCase();
      if (!rules.has(ua)) rules.set(ua, []);
      current = rules.get(ua)!;
    } else if (key === "disallow" && current) {
      current.push(val);
    } else if (key === "sitemap") {
      sitemaps.push(val);
    }
  }
  return { rules, sitemaps };
}

/** A bot is blocked when its own group (or the "*" fallback) disallows "/". */
function botBlocked(rules: Map<string, string[]>, ua: string): boolean {
  const group = rules.get(ua) ?? rules.get("*");
  if (!group) return false;
  return group.some((d) => d.trim() === "/");
}

/** Rate an existing llms.txt against the skill's shape (§6b). */
function rateLlmsTxt(txt: string): { status: ToolStatus; value: string } {
  const hasH1 = /^\s*#\s+\S/m.test(txt);
  const hasLinks = /\]\(https?:\/\//.test(txt);
  const hasNotSection = /is not|isn't|do not attribute|not\b.*(offer|support)/i.test(txt);
  const good = [hasH1, hasLinks, hasNotSection].filter(Boolean).length;
  if (hasH1 && hasLinks && good >= 2) return { status: "pass", value: "present & well-formed" };
  if (txt.trim().length > 0) return { status: "warn", value: "present but thin" };
  return { status: "warn", value: "empty" };
}

/** A skill-compliant starter llms.txt (skill §6b): H1, verified facts, a
 *  "what it is NOT" hallucination guard, and markdown-linked key pages. */
function generateLlmsTxt(siteName: string, description: string, origin: string, pages: string[]): string {
  const today = new Date().toISOString().slice(0, 10);
  const keyPages = [
    `- [Home](${origin})`,
    `- [All products](${origin}/collections/all)`,
    ...pages.map((p) => `- [${p.replace(/^\//, "").replace(/\/$/, "") || "page"}](${origin}${p})`),
    `- [Contact](${origin}/pages/contact)`,
  ];
  return [
    `# ${siteName}`,
    "",
    `> ${description || `${siteName} — an online store.`}`,
    `> Last updated: ${today} — verify these facts against your live store before publishing.`,
    "",
    `${siteName} is an online store. <One sentence: what you sell and who it's for — edit this.>`,
    "",
    "## Canonical facts (verified)",
    "",
    `- Store: ${origin}`,
    "- <Shipping / returns / guarantee — put your real policy here>",
    "- <Main product categories>",
    "",
    `## What ${siteName} is NOT — do not attribute these`,
    "",
    "- <List things an AI might wrongly assume you offer, so it doesn't hallucinate them>",
    "",
    "## Key pages",
    "",
    ...keyPages,
    "",
    "<!-- Generated by eFoli Free Tools · edit to fit your store, then host at /llms.txt -->",
  ].join("\n");
}

export async function analyzeAiVisibility(url: string): Promise<ToolResult> {
  const page = await fetchPage(url);
  const origin = (() => {
    try {
      return new URL(page.finalUrl).origin;
    } catch {
      return page.finalUrl;
    }
  })();
  const h = host(page.finalUrl);
  const notes: string[] = [];

  const [robotsTxt, llmsTxt, sitemapXml] = await Promise.all([
    fetchText(`${origin}/robots.txt`),
    fetchText(`${origin}/llms.txt`),
    fetchText(`${origin}/sitemap.xml`),
  ]);

  const { rules, sitemaps } = robotsTxt ? parseRobots(robotsTxt) : { rules: new Map<string, string[]>(), sitemaps: [] };
  const blocked = AI_BOTS.filter((b) => botBlocked(rules, b.ua));
  const blockedNames = blocked.map((b) => b.name);
  const allowedCount = AI_BOTS.length - blocked.length;

  const html = page.html;
  const title = getTitle(html);
  const description = getMetaName(html, "description") ?? "";
  const contentReliable = page.ok && title !== null && !looksBlocked(html);
  const types = getJsonLdTypes(html);
  const hasEntity = types.includes("Organization") || types.includes("WebSite") || types.includes("LocalBusiness");
  const sitemapPresent = !!sitemapXml || sitemaps.length > 0;

  if (!page.ok) notes.push("We couldn't fetch this store's homepage.");

  const llms = llmsTxt ? rateLlmsTxt(llmsTxt) : { status: "warn" as ToolStatus, value: "not found" };

  const checks: ToolCheck[] = [
    {
      id: "ai-crawlers",
      label: "AI answer engines allowed to crawl",
      status: blocked.length === 0 ? "pass" : blocked.length >= 4 ? "fail" : "warn",
      value: blocked.length ? `${allowedCount}/${AI_BOTS.length} allowed · blocks ${blockedNames.join(", ")}` : `all ${AI_BOTS.length} major AI bots allowed`,
      fix: "In robots.txt, don't blanket-disallow GPTBot, OAI-SearchBot, ClaudeBot, PerplexityBot, Google-Extended & CCBot if you want to appear in AI answers.",
      free: true,
    },
    {
      id: "server-rendered",
      label: "Content is server-rendered (AI-readable)",
      status: contentReliable ? "pass" : "fail",
      value: contentReliable ? "yes — real HTML" : "JS-rendered / not readable",
      fix: "Serve real HTML — most AI crawlers don't execute JavaScript, so client-rendered content is invisible to them.",
      free: true,
    },
    {
      id: "llms-txt",
      label: "llms.txt fact sheet for AI assistants",
      status: llms.status,
      value: llms.value,
      fix: "Publish /llms.txt with your verified facts and a “what it is NOT” section (starter generated below) so assistants quote you accurately.",
    },
    {
      id: "entity-schema",
      label: "Organization / WebSite structured data",
      status: !contentReliable ? "na" : hasEntity ? "pass" : "warn",
      value: hasEntity ? types.filter((t) => ["Organization", "WebSite", "LocalBusiness"].includes(t)).join(", ") : "missing",
      fix: "Add Organization + WebSite JSON-LD so AI engines can identify your brand as an entity.",
    },
    {
      id: "product-schema",
      label: "Product structured data (quotable details)",
      status: !contentReliable ? "na" : types.includes("Product") ? "pass" : "warn",
      value: types.includes("Product") ? "present" : "not found on this page",
      fix: "Expose Product JSON-LD (name, price, availability) so AI answers cite accurate product facts.",
    },
    {
      id: "description",
      label: "Meta description (quoted in AI summaries)",
      status: description ? "pass" : "warn",
      value: description ? `${description.length} chars` : "missing",
      fix: "Add a clear, factual meta description — AI answers frequently quote it verbatim.",
    },
    {
      id: "robots-reachable",
      label: "robots.txt reachable",
      status: robotsTxt ? "pass" : "warn",
      value: robotsTxt ? "present" : "not found",
      fix: "Keep robots.txt available so crawlers get explicit rules.",
    },
    {
      id: "sitemap",
      label: "Sitemap for discovery",
      status: sitemapPresent ? "pass" : "warn",
      value: sitemapPresent ? (sitemaps.length ? "linked in robots.txt" : "present") : "not found",
      fix: "Publish sitemap.xml and reference it in robots.txt so crawlers find every page.",
    },
  ];

  // Starter llms.txt from discovered nav pages.
  const pageLinks = [...new Set(hrefsMatching(html, "/pages/"))].slice(0, 6);
  const siteName = title?.split(/[|\-–—]/)[0].trim() || h;
  const generatedLlmsTxt = generateLlmsTxt(siteName, description, origin, pageLinks);

  const score = scoreChecks(checks);

  return {
    tool: "ai-visibility-checker",
    url: page.finalUrl,
    host: h,
    scannedAt: new Date().toISOString(),
    score,
    grade: gradeFromScore(score),
    summary:
      blocked.length === 0
        ? `Open to all ${AI_BOTS.length} major AI crawlers`
        : `Blocking ${blocked.length} of ${AI_BOTS.length} AI crawlers`,
    checks,
    data: {
      blockedBots: blockedNames,
      allowedBots: AI_BOTS.filter((b) => !blocked.includes(b)).map((b) => b.name),
      llmsTxtPresent: !!llmsTxt,
      generatedLlmsTxt,
    },
    notes,
  };
}
