/**
 * AI Visibility checker — can ChatGPT / Claude / Perplexity / Google AI reach and
 * quote this store? Checks robots.txt rules for AI crawlers, llms.txt presence,
 * and content quotability, then generates a starter llms.txt.
 */

import type { ToolCheck, ToolResult } from "../types";
import { fetchPage, fetchText, host } from "../http";
import { scoreChecks, gradeFromScore } from "../score";
import {
  getTitle,
  getMetaName,
  getJsonLdTypes,
  hrefsMatching,
  looksBlocked,
} from "@/lib/grader/html";

const AI_BOTS = [
  { ua: "gptbot", name: "GPTBot (OpenAI)" },
  { ua: "oai-searchbot", name: "OAI-SearchBot (ChatGPT search)" },
  { ua: "chatgpt-user", name: "ChatGPT-User" },
  { ua: "claudebot", name: "ClaudeBot (Anthropic)" },
  { ua: "perplexitybot", name: "PerplexityBot" },
  { ua: "google-extended", name: "Google-Extended (Gemini)" },
  { ua: "ccbot", name: "CCBot (Common Crawl)" },
];

/** Parse robots.txt into UA (lowercased) → disallow paths. */
function parseRobots(robots: string): Map<string, string[]> {
  const map = new Map<string, string[]>();
  let current: string[] = [];
  for (const raw of robots.split("\n")) {
    const line = raw.split("#")[0].trim();
    if (!line) continue;
    const [k, ...rest] = line.split(":");
    const key = k.trim().toLowerCase();
    const val = rest.join(":").trim();
    if (key === "user-agent") {
      const ua = val.toLowerCase();
      if (!map.has(ua)) map.set(ua, []);
      current = map.get(ua)!;
    } else if (key === "disallow" && current) {
      current.push(val);
    }
  }
  return map;
}

function botBlocked(map: Map<string, string[]>, ua: string): boolean {
  const group = map.get(ua) ?? map.get("*");
  if (!group) return false;
  return group.some((d) => d === "/");
}

function generateLlmsTxt(siteName: string, description: string, origin: string, pages: string[]): string {
  const lines = [
    `# ${siteName}`,
    "",
    `> ${description || `${siteName} — online store.`}`,
    "",
    "## Key pages",
    `- [Home](${origin})`,
    `- [All products](${origin}/collections/all)`,
    ...pages.map((p) => `- [${p.replace(/^\//, "").replace(/\/$/, "") || "page"}](${origin}${p})`),
    "",
    "## About",
    `- Contact: ${origin}/pages/contact`,
    "",
    "<!-- Generated by eFoli Free Tools. Edit to fit your store. -->",
  ];
  return lines.join("\n");
}

export async function analyzeAiVisibility(url: string): Promise<ToolResult> {
  const page = await fetchPage(url);
  const origin = (() => {
    try {
      return new URL(page.finalUrl).origin;
    } catch {
      return page.finalUrl;
    }
  })();
  const h = host(page.finalUrl);
  const notes: string[] = [];

  const [robotsTxt, llmsTxt] = await Promise.all([
    fetchText(`${origin}/robots.txt`),
    fetchText(`${origin}/llms.txt`),
  ]);

  const map = robotsTxt ? parseRobots(robotsTxt) : new Map<string, string[]>();
  const blocked = AI_BOTS.filter((b) => botBlocked(map, b.ua));
  const blockedNames = blocked.map((b) => b.name);

  const html = page.html;
  const title = getTitle(html);
  const description = getMetaName(html, "description") ?? "";
  const contentReliable = page.ok && title !== null && !looksBlocked(html);
  const hasSchema = getJsonLdTypes(html).length > 0;

  if (!page.ok) notes.push("We couldn't fetch this store's homepage.");

  const checks: ToolCheck[] = [
    {
      id: "ai-crawlers",
      label: "AI crawlers allowed (not blocked in robots.txt)",
      status: blocked.length === 0 ? "pass" : blocked.length >= 4 ? "fail" : "warn",
      value: blocked.length ? `blocks ${blockedNames.join(", ")}` : "all major AI crawlers allowed",
      fix: "Allow GPTBot, OAI-SearchBot, ClaudeBot, PerplexityBot & Google-Extended if you want AI-search visibility.",
      free: true,
    },
    {
      id: "robots",
      label: "robots.txt reachable",
      status: robotsTxt ? "pass" : "warn",
      value: robotsTxt ? "present" : "not found",
      fix: "Keep robots.txt available so crawlers get clear rules.",
      free: true,
    },
    {
      id: "llms-txt",
      label: "llms.txt present",
      status: llmsTxt ? "pass" : "warn",
      value: llmsTxt ? "present" : "not found",
      fix: "Add an llms.txt to guide AI assistants to your key pages (generated below).",
    },
    {
      id: "server-rendered",
      label: "Content is server-rendered (AI-quotable)",
      status: contentReliable ? "pass" : "fail",
      value: contentReliable ? "yes" : "JS-rendered / not readable",
      fix: "Serve real HTML content — AI crawlers often don't execute JavaScript.",
    },
    {
      id: "schema",
      label: "Structured data present (helps AI understand)",
      status: hasSchema ? "pass" : "warn",
      value: hasSchema ? "present" : "missing",
      fix: "Add Product/Organization JSON-LD so AI answers cite accurate details.",
    },
    {
      id: "description",
      label: "Meta description (used in AI summaries)",
      status: description ? "pass" : "warn",
      value: description ? `${description.length} chars` : "missing",
      fix: "Add a clear meta description — AI answers often quote it.",
    },
  ];

  // Starter llms.txt from discovered nav pages.
  const pageLinks = [...new Set(hrefsMatching(html, "/pages/"))].slice(0, 6);
  const siteName = title?.split(/[|\-–—]/)[0].trim() || h;
  const generatedLlmsTxt = generateLlmsTxt(siteName, description, origin, pageLinks);

  const score = scoreChecks(checks);

  return {
    tool: "ai-visibility-checker",
    url: page.finalUrl,
    host: h,
    scannedAt: new Date().toISOString(),
    score,
    grade: gradeFromScore(score),
    summary:
      blocked.length === 0
        ? "Your store is open to major AI crawlers"
        : `Blocking ${blocked.length} AI crawler(s)`,
    checks,
    data: { blockedBots: blockedNames, llmsTxtPresent: !!llmsTxt, generatedLlmsTxt },
    notes,
  };
}
